Do not clear tests group if test_group_path is the same as project_group_path
rambler-digital-solutions/Generamba pull request #193
Opened 2017-08-07 09:45 UTC by RamTararam

There is no need to clear the same group twice when tests are placed alongside with feature implementation.

2017-08-07 12:01 UTC, Brain89 requested changes

2017-08-07 12:01 UTC, Brain89 commented on lib/generamba/module_generator.rb
> +			XcodeprojHelper.clear_group(project, targets, group_path) if clear_group
Думаю, лучше сразу на уровне метода **process_files_if_needed** формировать этот флаг. Действие по очистке группы внутри проектного файла смотрится как дополнительное и не является необходимым для выполнения метода. Поэтому предлагаю флаг **clear_group** убрать из интерфейса метода

2017-08-07 15:30 UTC, RamTararam commented on lib/generamba/module_generator.rb
> +			XcodeprojHelper.clear_group(project, targets, group_path) if clear_group
Внутри `process_files_if_needed` у нас недостаточно информации для решения стоит ли чистить группы. А именно нам нужно проверить: чистили ли мы уже эту группу или нет (или, по-другому, совпадает ли группа для тестов с группой для кода).

Поэтому, правильно ли я понимаю, что очистку групп надо будет убрать из `process_files_if_needed` и  делать в самом вызывающем коде, то есть в `generate_module`?

2017-08-08 08:16 UTC, Brain89 commented on lib/generamba/module_generator.rb
> +			XcodeprojHelper.clear_group(project, targets, group_path) if clear_group
Давай передадим в метод process_files_if_needed не флаг, а вот этот параметр **code_module.project_group_path**. И у нас будет достаточно информации. Тогда, если я правильно понимаю, сам метод сможет принимать решение, как ему управлять группой внутри проекта.

2017-08-09 13:05 UTC, Brain89 approved these changes

2017-08-10 14:22 UTC, kkivan approved these changes

2017-08-10 16:34 UTC, merged